# -*- coding: utf-8 -*-
"""SalaryPrediction_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mjzHFvenOMavRJZTaSoNAVoOkIjjtJ5W

Salary Prediction using Machine Learning Algorithm

Importing Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

datafile = pd.read_csv('/Salary_Data.csv')

datafile

x = datafile.iloc[:,:1].values

y = datafile.iloc[:,1:].values

fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
ax.scatter(x,y,color='blue')

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

from sklearn.linear_model import LinearRegression

regressor = LinearRegression()

regressor.fit(x_train,y_train)

y_prediction=regressor.predict(x_test)

y_prediction

y_test

plt.scatter(x,y,color='green')
plt.plot(x,regressor.predict(x),color='yellow')

from sklearn.preprocessing import PolynomialFeatures

poly=PolynomialFeatures(degree=2)
x_poly=poly.fit_transform(x)

regressor.fit(x_poly,y)

plt.scatter(x,y,color='r')
plt.plot(x,regressor.predict(poly.fit_transform(x)),color='blue')

y_pred=regressor.predict(poly.fit_transform(x))

y_prediction

y